version: '3'
services:
    mysql:
        image: mysql:5.7        
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
        expose:
        # Opens port 3306 on the container
        - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: processoSeletivo2021_Eduardo_Marinho
        volumes:
            - ./volumes/mysql:/var/lib/mysql
